### ISSUE TITLE
Fix the Readme workflow status picture

### ISSUE THREAD

**Issue by tigroo** [Orange-OpenSource/its-client#110]
The "Python" workflow was deleted, replaced by a collection of Workflow.
Why not to bundle these collection to one, called "Python"

**Comment by tigroo** [comment]
Expected: the new Python workflow is badged on the readme, like previously.

**Comment by ymorin-orange** [comment]
The problem is that there is no single python workflow; instead, there is one
workflow for each python module (client or lib).

So, we can't have a single badge, we'd need to add one badge for each python
module, which I'm afraid is going to be a bit too much: currently 5 on master,
with more to come...

**Comment by nbuffon** [comment]
As discussed together badges will be shown in the main README.md in dedicated sections mentioning Python subdirs
